share: "Share This"
email: "Email"
title: "My Example Site"
shorttitle: "Example"
description: ""
aboutus: "About Us"
contact: "Contact"
phone: "Phone"
submit: "Submit"
yourname: "Your Name"
youremail: "Your Email Address"
comments: "Comments"
back: "Back"
siteby: "Site by"
emailfriend: "Email a Friend"
recipientsemail: "Recipent's Email"
message: "Message"
cancel: "Cancel"
send: "Send"
profile: "Profile"
clients: "Clients"
categories: "Categories"
facebook: "Facebook"
twitter: "Twitter"
